language: python
python:
    - "3.8"
install:
    - "pip install pipenv"
    - "pipenv sync"
script: "python -m unittest discover time_management *_test.py"
notifications:
    slack: tm-oma8428:uCBO1vn5YEp63UlSG2r1CCBf
